cuda: "all"
model:
    arch: resnet
    depth: 50
data:
    dataset: imagenet
#    train_dir: /gpfs/home/qlli/ywen/syt/dataset/ILSVRC/train
#    val_dir: /gpfs/home/qlli/ywen/syt/dataset/ILSVRC/val
    train_dir: /data/home/ywen/syt/dataset/ILSVRC/train
    val_dir: /data/home/ywen/syt/dataset/ILSVRC/val
    workers: 16
training:
    runid: 1 #label smooth
#    runid: 101 #cross entropy
#    seed: 1337
    epochs: 100
    batch_size: 256
    loss:
#        name: 'cross_entropy'
        name: 'label_smooth'
        smoothing: 0.1
    optimizer:
        name: 'sgd'
        lr: 0.1  #for imagenet, lr = 0.1 * batch_size / 256
        weight_decay: 0.0001
        momentum: 0.9
    lr_schedule:
        name: 'multi_step'
        milestones: [30,60,90]
        gamma: 0.1
    save_interval: 1
    resume: save_model.pkl
    best_model: best_model.pkl